#+title: Continuous Compounding the Hard Way
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup


* Differential Equation for Continuous Compounding

Differential equations are equations which include variables and their derivatives.  Let V be our present amount of money, and let it be compounded continuously at /Q/.  Then we can write:

$$\frac{dV}{V} = Qdt$$

This says the percent change in value over the next instant is the quoted interest rate times and instantaneous length of time.

** Future Value

We can use this differential equation to find the future value of some amount.  For example, say we have $100 today.  How much will this $100 be in 3 years if it is compounded continuously with an annual 5% rate?  Let /FV/ denote the future value.

$$\int_{100}^{FV}\frac{dV}{V} = \int_{t=0}^3 0.05dt$$
$$ln(FV) - ln(100) = 0.05(3) \Rightarrow e^{ln(FV)} = e^{ln(100) + 0.05(3)} \Rightarrow FV = 100e^{0.05(3)} = 116.18$$

The future value is $116.18.  

Note, if in the above we let the present value, quoted rate, and number of years be denoted by /PV/, /Q/, and /t/ respectively, we have:

$$FV = PVe^{Qt}$$

** Present Value

Say instead we know the future value, $116.18, and want to know the present value.

$$\int_{PV}^{116.18}\frac{dV}{V} = \int_{t=0}^3 0.05dt$$
$$ln(116.18) - ln(PV) = 0.05(3) \Rightarrow PV = 116.18e^{-0.05(3)} = 100$$

** Time to Reach a Given Amount

How many years will it take for $100 to become $140?  

$$\int_{100}^{140}\frac{dV}{V} = \int_{t=0}^T 0.05dt$$
$$ln(140) - ln(100) = 0.05(3) \Rightarrow T = \frac{ln(140) - ln(100)}{0.05} = 6.73$$

It will take 6.73 years.

*** Time to Double

Let's say we want to know how many years it will take to double our money to $200.  

$$\int_{100}^{200}\frac{dV}{V} = \int_{t=0}^T 0.05dt$$
$$ln(200) - ln(100) = 0.05(T) \Rightarrow T = \frac{ln(200) - ln(100)}{0.05} = 13.86$$

It will take 13.86 years.

** Rate Required

Let's say we want to know what rate of return (/Q/) we will have to earn per year to have $175 in 10 years.  

$$\int_{100}^{175}\frac{dV}{V} = \int_{t=0}^10 Qdt$$
$$ln(175) - ln(100) = Q(10) \Rightarrow Q = \frac{ln(175) - ln(100)}{10} = 0.05596$$

We will have to earn about 5.60% per year.

* /FV/ Equation The Easy Way

You might say it is easier to just use the formula for the Future Value you get from your textbook:

$$FV = e^{rT}$$

You can rearrange this formula to answer any of the above questions.  However how did your text get this formula? It usually does the foloowing.

Let /Q/ be the annual stated rate, and let there be /m/ compounding periods.  Then the /Effective Annual Rate/ is:

$$EAR = (1 + \frac{Q}{m})^m - 1$$

Letting the number of compounding periods increase to infinity we have:

$$lim_{n\to\infty} = (1 + \frac{Q}{m})^m - 1 = e^{Q} - 1$$

Using this rate we have:

$$FV = PV(1 + r)^t = PV(1 + e^{Q} - 1)^t = PVe^{Qt}$$

The only issue is your text probably didn't explain how $(1 + \frac{Q}{m})^m - 1 = e^{Q} - 1$ in the limit---it just says it does.

* Alternative Differential Equation Derivation of $FV=e^{Qt}$

We can set up the following differential equation.  This is just a modification of our above approach.  Here $\frac{dV}{dt} is the rate of change of the value of our investment, and $QV$ is the rate at which interest increases.

$$\frac{dV}{dt} = QV$$

Also say we know our present value, $V_0$ or more commonly /PV/.  We can solve this equation as follows:












* [[https://en.wikipedia.org/wiki/Flesch%25E2%2580%2593Kincaid_readability_tests][Reading Ease Score]]

#+BEGIN_SRC elisp :results output :exports results
(print (writegood-reading-ease))
#+END_SRC

#+RESULTS:
: 
: "Flesch-Kincaid reading ease score: 117.89 Very easy (5th grade)"

#+BEGIN_SRC elisp :results output :exports results
(print (writegood-grade-level))
#+END_SRC

#+RESULTS:
: 
: "Flesch-Kincaid grade level score: -0.10"
