#+title: Continuous Compounding the Hard Way
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

* Continuous Compounding



* Differential Equation

Differential equations are equations which include variables and their derivatives.  Let V be our present amount of money, and let it be compounded continuously at /Q/.  Then we can write:

$$\frac{dV}{V} = Qdt$$

** Future Value

We can use this differential equation to find the future value of some amount.  For example, say we have $100 today.  How much will this $100 be in 3 years if it is compounded continuously with an annual 5% rate?  Let /FV/ denote the future value.

$$\int_{100}^{FV}\frac{dV}{V} = \int_{t=0}^3 0.05dt$$
$$ln(FV) - ln(100) = 0.05(3) \Rightarrow e^{ln(FV)} = e^{ln(100) + 0.05(3)} \Rightarrow FV = 100e^{0.05(3)} = 116.18$$

The future value is $116.18.  

** Present Value

Say instead we know the future value, $116.18, and want to know the present value.

$$\int_{PV}^{116.18}\frac{dV}{V} = \int_{t=0}^3 0.05dt$$
$$ln(116.18) - ln(PV) = 0.05(3) \Rightarrow PV = 116.18e^{-0.05(3)} = 100$$

** Time to Reach a Given Amount

How many years will it take for $100 to become $140?  

$$\int_{100}^{140}\frac{dV}{V} = \int_{t=0}^T 0.05dt$$
$$ln(140) - ln(100) = 0.05(3) \Rightarrow T = \frac{ln(140) - ln(100)}{0.05} = 6.73$$

It will take 6.73 years.

*** Time to Double

Let's say we want to know how many years it will take to double our money to $200.  

$$\int_{100}^{200}\frac{dV}{V} = \int_{t=0}^T 0.05dt$$
$$ln(200) - ln(100) = 0.05(T) \Rightarrow T = \frac{ln(200) - ln(100)}{0.05} = 13.86$$

It will take 13.86 years.

** Rate Required









* /FV/ Equation

** The Easy Way

Let /Q/ be the annual stated rate, and let there be /m/ compounding periods.  Then the /Effective Annual Rate/ is:

$$EAR = (1 + \frac{Q}{m})^m - 1$$

Letting the number of compounding periods increase to infinity we have:

$$lim_{n\to\infty} = (1 + \frac{Q}{m})^m - 1 = e^{Q} - 1$$


** Via Differential Equation








* [[https://en.wikipedia.org/wiki/Flesch%25E2%2580%2593Kincaid_readability_tests][Reading Ease Score]]

#+BEGIN_SRC elisp :results output :exports results
(print (writegood-reading-ease))
#+END_SRC

#+RESULTS:
: 
: "Flesch-Kincaid reading ease score: 81.69 Easy (6th grade)"

#+BEGIN_SRC elisp :results output :exports results
(print (writegood-grade-level))
#+END_SRC

#+RESULTS:
: 
: "Flesch-Kincaid grade level score: 5.28"
